### ISSUE TITLE
Wayfire starts with XDG_CURRENT_DESKTOP either unset or set to previous session's desktop

### ISSUE THREAD

**Issue by kode54** [Vladimir-csp/uwsm#1]
XDG_CURRENT_DESKTOP ends up set to either GNOME if I was last using a GNOME session on my desktop before rebooting, or nothing at all. WAYFIRE_LOCAL_CONFIG remains unset by the tweaks function, so the unit that starts Wayfire starts it with a `-c` switch, but no config path.

**Comment by Vladimir-csp** [comment]
Does `${XDG_CONFIG_HOME}/wayfire/wayfire.ini` exist after launch attempt?

**Comment by Vladimir-csp** [comment]
I've added more conditions on config file search, but that may not address this problem directly.
Could you post `journalctl --user -u wayland-session-wayfire.scope` (if you launched via `shell-intstart`) or `journalctl --user -u wayland-wm-env@wayfire.service` (if you launched via `sd-start` or `wayland-wm@wayfire.service` service directly)

**Comment by kode54** [comment]
I launched it via the `.profile` snippet. Well, I adapted it for `.zprofile`.

**Comment by kode54** [comment]
Here's a log output.

[wayland-session-env.txt](https://github.com/Vladimir-csp/uwsm/files/9654513/wayland-session-env.txt)

**Comment by Vladimir-csp** [comment]
Are those vars with `%%` specific for zsh environment?
looks like systemctl errors out and does nothing, I'll look into this.

**Comment by Vladimir-csp** [comment]
Looks like your environment has something that should not exist there.
This case seems relevant: https://access.redhat.com/discussions/4124031.

Can you determine where those illegal vars come from? `env` or `systemctl --user show-environment` or both?

For now I've added exit with error on failure to run import-environment. The assumption is that the actual environment can not contain vars with illegal names. Maybe I'll add a filter later.

**Comment by kode54** [comment]
Apparently, I had `env-modules` installed, and I forgot that. That's apparently an AUR package, so it's not even official on Arch.

**Comment by Vladimir-csp** [comment]
I've added a filter function for all processing of `env` output, please try running again with illegal vars. Error messages will be logged by `wayland-wm-env@*.service`, but everything should work.
