### ISSUE TITLE
docs: uwsm nested desktop entry 

### ISSUE THREAD

**Issue by kai-tub** [Vladimir-csp/uwsm#35]
Hey,

Sorry, I have a question regarding the documentation about [starting from a display manager](https://github.com/Vladimir-csp/uwsm?tab=readme-ov-file#from-a-display-manager).
The docs say:

> Things to keep in mind:
> [...]
> - It should not launch a desktop entry, only an executable.

Why shouldn't one enter a desktop entry?
I'm just curious about why this isn't recommended since `uswm start --help` does provide an option to start a desktop entry.

Thanks!

**Comment by Vladimir-csp** [comment]
I will revisit the code, maybe it can be softened down to not the same Entry ID.

**Comment by Vladimir-csp** [comment]
It might get harder than it looks due to some chicken and egg problems with re-reparsing args.
