### ISSUE TITLE
Transparent absolute paths support for compositors

### ISSUE THREAD

**Issue by Vladimir-csp** [Vladimir-csp/uwsm#36]
Would be useful for operating in Nix infrastructure.
Already in progress, but introduces complexity and clashes with simple "launch via just unit specifier" concept. So needs testing and refactoring. Currently executable paths are supported, not entries.

**Comment by JohnRTitor** [comment]
> Currently executable paths are supported, not entries.

Having Desktop entry paths supported would be nice. As jtojar has pointed out in https://github.com/Vladimir-csp/uwsm/pull/34#issuecomment-2256815495 we could pass the path of Hyprland desktop entry easily on NixOS by using 
```nix
"${config.services.displayManager}/share/wayland-sessions/hyprland.desktop"
```

Our main idea here is to create a  `hyprland_uwsm.desktop` file which will start `uswm` with a link to the actual `hyprland.desktop`.

**Comment by JohnRTitor** [comment]
Just tried the 0.17.3, it looks like this still does not work by path, unless `Hyprland` is found and in path.

**Comment by Vladimir-csp** [comment]
Preloader also needs to be aware of path, fixed.

**Comment by JohnRTitor** [comment]
Sweet, looks like running compositors by their bin path fully works now, without any manual intervention. 

But still desktop files by path support is lacking it seems? 

![IMG_20240731_231329](https://github.com/user-attachments/assets/71d650b3-c707-4750-bf06-6f4d909180b6)

**Comment by Vladimir-csp** [comment]
Yes.
I'm trying to find a more elegant solution for the whole drop-in generator. I'm not comfortable with current code complexity.

**Comment by kai-tub** [comment]
the full path option in v0.17.4 also works for me  :+1: 

Thank you both for working on the nix support & testing :bow: 

PS: Sorry for the delay, I am dealing with a failing BTRFS Raid array....

**Comment by Vladimir-csp** [comment]
There is a problem with the current implementation: when hardcoding command with path, `uwsm aux`  commands will have different compositor ID than implied in start command. This might not cause immediate problems, but sets up potential disruptions for plugins and anything that relies on various variables.

Is there really no way to to make desktop entries and executables consistently discoverable in Nix?

**Comment by Vladimir-csp** [comment]
> In NixOS there is directory where every compositors desktop entry resides much like a normal FHS environment's
Is it included in `$XDG_DATA_DIRS` visible by display managers, and user environments?

**Comment by JohnRTitor** [comment]
As explained by @jtojnar in https://github.com/Vladimir-csp/uwsm/pull/34#issuecomment-2256815495, in the case of GDM, NixOS passes the `XDG_DATA_DIRS` env variable to `displayManager.service` which contains the path of all WM sessions.

For LightDM and SDDM, the path is passed/hardcoded in the DM's config file, so it can find it.

**Comment by Vladimir-csp** [comment]
Is it available in user environment?

**Comment by JohnRTitor** [comment]
It's probably not, though I might be wrong on this one.

**Comment by kai-tub** [comment]
> Is there really no way to to make desktop entries and executables consistently discoverable in Nix?

Maybe we have to change the perspective a bit. Currently, we are trying to make the `uwsm` package _work out of the box_ for nix. But maybe we should opt for a "pure" NixOS module solution. By defining something like `programs.uwsm` or `services.uwsm`, we could probably come up with one way or another to inject the `XDG_DATA_DIRS` environment variable before executing `uwsm`.  

But this means that the standalone `uwsm` package might not work as expected for a user that doesn't use the NixOS module. @JohnRTitor, you have much more experience on the NixOS side. Do you think this is a viable solution?

Otherwise, we could revert back to injecting the (wrong/not overlayed) wayland compositors paths from within the package for those who really need it.

**Comment by Vladimir-csp** [comment]
Plus I'm considering using systemd generators in the future, so user's systemd has to be able to discover entries in `$XDG_DATA_HOME:$XDG_DATA_DIRS`

**Comment by JohnRTitor** [comment]
> But this means that the standalone uwsm package might not work as expected for a user that doesn't use the NixOS module. 

That's an entirely fine approach. In NixOS, DEs and many other programs are supposed to be used by turning on their respective option, not by adding them to `environment.systemPackages`. There's so much a package can do without a NixOS option.

**Comment by JohnRTitor** [comment]
Alternatively, uwsm could source a config file from `/etc/uwsm/default.conf` like many other packages does (like `apt/sources.list.d` on debian).

```
XDG_DATA_DIRS=/nix/store/HASH-NAME/share/wayland-sessions
XDG_DATA_HOME=/home/$USER/.local/share
```

uwsm could ready the following content and act as these are provided by XDG_DATA_DIRS, and other variables and utilise them.

On the NixOS side, a package can not create these configuration files by itself however, we can create them in `/etc` using NixOS options.

**Comment by Vladimir-csp** [comment]
> Alternatively, uwsm could source a config file from /etc/uwsm/default.conf like many other packages does (like apt/sources.list.d on debian).

I would prefer not to read environment vars from a config when there are environment vars in the actual environment. )

With 7e46a04 I'm still not happy with complexity, but there are no obvious inconsistencies. `uwsm` in units always receives correct ID and stays dynamic unless executable is explicitly added. And the new '-F` key allows forcing fully rendered command line with path as seen by `uwsm start`.

**Comment by Vladimir-csp** [comment]
With v0.18.0 hardcode mode is finished. It can be either explicit (`-F`), or triggered by a path in command line or entry's `Exec`.
Please test.
