### ISSUE TITLE
Exiting compositor now leaves several services dangling

### ISSUE THREAD

**Issue by kode54** [Vladimir-csp/uwsm#37]
Now I have to manually issue:

```
systemctl --user restart xdg-desktop-portal
```

After logging back in, as `xdg-desktop-portal` itself is left dangling indefinitely, but none of the other `xdg-desktop-portal-*` daemons are.

**Comment by kode54** [comment]
Seems this is also leaving mako dangling, and mako not only fails to start up again, but the existing instance has no display to appear on.

Here's a journal excerpt:

[uwsm-labwc-startup.log.txt](https://github.com/user-attachments/files/16538681/uwsm-labwc-startup.log.txt)

**Comment by Vladimir-csp** [comment]
Does not happen on my machine (portals).

Mako (and dunst which I use) are activated via dbus, so they go to `app.slice` and do not receive deactivation jobs from uwsm-managed units. Dunst ends on its own when wayland ends, perhaps mako does not do that.

You can hook `mako.service` to graphical slice by adding a drop-in to it with:
```
systemctl --user edit --stdin --drop-in slice.conf mako.service << EOF
[Service]
Slice=app-graphical.slice
EOF
```

It seems that gtk portal on your systetm dies a lot, this may indicate a misconfiguration or other problem.

Did your problem start since a specific uwsm version? Does it go away by downgrading?

**Comment by Vladimir-csp** [comment]
@kode54 I'm inclined to close this. Do you have any additional info?

**Comment by kode54** [comment]
Sorry, it seems that rather than dangling services, I've got startups failing to happen. And from my dmesg log, it looks like several services are expecting WAYLAND_DISPLAY to be populated early, as their output is logging into the journal at the same time as the uwsm output reporting which environment variables are being populated into the environment.

**Comment by Vladimir-csp** [comment]
Portals have dbus-activated units, maybe something triggers them early.
Also the first thing starting is kde portal. What happens if you remove it?

**Comment by Vladimir-csp** [comment]
Alternatively, try this:
```
mkdir -p ~/.config/systemd/user/xdg-desktop-portal.service.d ~/.config/systemd/user/xdg-desktop-portal-.service.d
cat << EOF > ~/.config/systemd/user/xdg-desktop-portal.service.d/50-ordering.conf 
[Unit]
After=graphical-session-pre.target
EOF
cat << EOF > ~/.config/systemd/user/xdg-desktop-portal-.service.d/50-ordering.conf 
[Unit]
After=graphical-session-pre.target
EOF
systemctl --user daemon-reload
```
If this fixes the problem and does not break anything else, I might include this in uwsm's units generator.

**Comment by Vladimir-csp** [comment]
Edited `s/session-pre/session/'

**Comment by Vladimir-csp** [comment]
Wrong idea, but maybe not the wrong direction. 
xdg-desktop-portal-wlr is already correctly ordered `After=graphical-session.target`. But -gtk lacks ordering, and -kde is ordered `After=plasma-core.target`. 
`xdg-desktop-portal-.service.d` glob also applied to `xdg-desktop-portal-rewrite-launchers.service` which should be launched at -pre. This forces to apply drop-ins individually.

**Comment by Vladimir-csp** [comment]
Although you still might try adding `After=graphical-session.target` to kde and gtk portals specifically, who knows.

**Comment by kode54** [comment]
> Although you still might try adding `After=graphical-session.target` to kde and gtk portals specifically, who knows.

Thanks for the hint, I also added this to the xdg-desktop-portal.service with `systemctl --user edit`. Everything appears to be working now.

**Comment by Vladimir-csp** [comment]
@kode54 Could you please check if removing ordering modification specifically from `xdg-desktop-portal.service.in` affects the fix?

**Comment by kode54** [comment]
The `xdg-desktop-portal` override is not needed, only the portals themselves. And the KDE one stops the KDE portal from crashing itself on every login.
