### ISSUE TITLE
Python rewrite

### ISSUE THREAD

**Issue by Vladimir-csp** [Vladimir-csp/uwsm#4]
The plan so far:
Build basic structure around argparse subparsers.
Use shell insert for environment preparation, keep this section of plugin support.
Scope of potential python code plugins is undecided as of yet, maybe hold off until a working prototype is released.
Cover #3 out of the box.

- [x] Working prototype ([py](https://github.com/Vladimir-csp/uwsm/tree/py))
- [x] Update manuals
- [ ] Decide on python-side plugins
- [x] Desktop entry support in `app` subcommand (namely proper handling of various `%*` fields)
  - [x] launching without arguments (drop % fields)
  - [x] non-argument % fields support
  - [x] argument fields support

**Comment by skewballfox** [comment]
would you like help with this? way more comfortable with python than I am with bash

**Comment by Vladimir-csp** [comment]
Sure! My python skills are just sufficient for writing something that works, but prone to occasional microscope-driven nails.

**Comment by skewballfox** [comment]
Have any preferences as far as build tools you have any preferences? I'm preferential to pipenv or poetry, and can use either to generate a list of compatible dependency versions.

**Comment by Vladimir-csp** [comment]
No preferences, my wokrflow is just a text editor and a couple of consoles.

**Comment by Vladimir-csp** [comment]
@skewballfox Do you have any suggestions on how to implement python-based plugins and what would they be useful for?
Currently shell plugins only affect environment preparations (or any action a shell can do from -env unit).

**Comment by Vladimir-csp** [comment]
No need to keep this open, will return to python-based plugins when explicit need arises.
