### ISSUE TITLE
Option to disable logging apps' output to the journal

### ISSUE THREAD

**Issue by kode54** [Vladimir-csp/uwsm#42]
It's really annoying, especially when some apps just outright spam their stdout nonstop, like Electron and Chromium do right now when capturing my webcam.

**Comment by Vladimir-csp** [comment]
I thought about incorporating some solution for this either in `uwsm app` or `uuctl`, but not sure on details yet.

I usually override those in `~/.local/share/applications` by wrapping in `sh -c`, playing dirty.
Alternatively, arguably more cleanly, this can be done via a drop-in for service template, i.e. for `app-Hyprland-chromium@.service`.
`systemctl --user edit --force --drop-in=mute.conf app-Hyprland-chromium@.service` does not seem to work despite manpage saying `--force` should help. So we are left with manual config, which works:
```
mkdir -p "${XDG_CONFIG_HOME}/systemd/user/app-Hyprland-chromium@.service.d/"
cat <<- EOF > "${XDG_CONFIG_HOME}/systemd/user/app-Hyprland-chromium@.service.d/mute.conf"
[Service]
StandardOutput=null
StandardError=null
EOF
systemctl --user daemon-reload
```

It will not work for scopes, but those are connected to existing stdout/stderr anyway.

**Comment by kode54** [comment]
I'll try the override method, or at least using grep to filter the specific message. It's also a Flatpak app, so I'm not sure if filtering the flatpak binary running it will have the same effect.
