### ISSUE TITLE
GTK applications throw assertion failures and crash

### ISSUE THREAD

**Issue by KZDKM** [Vladimir-csp/uwsm#46]
When I start hyprland with `uwsm start -S -- Hyprland`, some gtk applications would show warning relating `g_is_variant_of_type` assertion failures in output seen in `journalctl` (seen with blackbox-terminal). [AGS](https://github.com/Aylur/ags) also crashes with with similar error. I have tried launching from GDM and from tty, as well as disabling all autostart entries but the issue persists.

**Comment by Vladimir-csp** [comment]
Many appplications spam a lot of stuff to stdout/stderr, which goes to journal when they are started as systemd services. I doubt this is uwsm-related. Check if running them from a terminal  or as a scope differs.

Also `uwsm app` recently got `-S` option to run apps with suppressed stdout/stderr/both. `uuctl` can also persistently silence service units by their template unit IDs.

Feel free to reopen this if you identify any environment preset by uwsm causing problems.
