### ISSUE TITLE
Zombie child process of compositor

### ISSUE THREAD

**Issue by c4rlo** [Vladimir-csp/uwsm#47]
I use uwsm 0.20.1 with sway, and am finding that my `sway` process consistently has a child process in zombie status named "uwsm":

![image](https://github.com/user-attachments/assets/b49a33cc-cb0b-4aec-9c39-af0ebb8ce041)

The zombie PID, 5129, features in the journal as follows:

```
Sat 2024-11-02 17:02:47 GMT user@1000.service/wayland-wm@sway.service[5128]: Starting: sway...
[...]
Sat 2024-11-02 17:02:47 GMT user@1000.service/wayland-wm@sway.service[5129]: Expecting variables to appear in activation environment:
Sat 2024-11-02 17:02:47 GMT user@1000.service/wayland-wm@sway.service[5129]:   I3SOCK, WAYLAND_DISPLAY, SWAYSOCK
[...]
Sat 2024-11-02 17:02:47 GMT user@1000.service/wayland-wm@sway.service[5129]: All expected variables appeared in activation environment.
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]: Exporting variables to systemd user manager:
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]:   I3SOCK (already set)
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]:   SWAYSOCK (already set)
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]:   WAYLAND_DISPLAY (already set)
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]:   XCURSOR_SIZE (already set)
Sat 2024-11-02 17:02:48 GMT user@1000.service/wayland-wm@sway.service[5129]: Unit for sway is already active.
```

I was curious what's going on, and believe it is because of the behaviour of `uwsm aux exec`, specifically these lines:

https://github.com/Vladimir-csp/uwsm/blob/56cf0082b5f4340805f04e100810ee1d2bfa966d/uwsm/main.py#L4829-L4838

The parent process does not wait for the child process, and instead immediately proceeds to `exec` the compositor. This leaves the compositor with the zombie child.

A simple fix for this would be to use a double fork. If that sounds reasonable, I'm happy to submit a PR with such a change.

**Comment by Vladimir-csp** [comment]
I completely missed that. PR is very welcome, thank you!
