### ISSUE TITLE
Questions about `uwsm app`

### ISSUE THREAD

**Issue by fufexan** [Vladimir-csp/uwsm#53]
I've been in the process of integrating uwsm into my desktop experience since [the discussion in Hyprland](https://github.com/hyprwm/Hyprland/pull/8339). So far I've done the [first part](https://github.com/fufexan/dotfiles/commit/a6084b9eec934ab9cbb452eb9accd2c20bb38444), aka starting Hyprland via uwsm. The second part would entail launching apps through `uwsm app`.

I currently use [anyrun](https://github.com/anyrun-org/anyrun) as my runner. It does not have a `--launch-prefix` option like fuzzel does, but I've been integrating it myself. I've hit a roadblock in deciding whether to pass Exec or the Desktop Entry path to `uwsm app --` (or the `launch_prefix`, to be precise). Is there any benefit to using one over the other?

The next question would be how to handle starting terminal applications from anyrun:
1. `sh -c ${terminal} -e ${launch_prefix} ${entry.exec}` (or `${entry.path}`, if that's more appropriate)
2. `sh -c ${launch_prefix} ${terminal} -e ${entry.exec}`

**Comment by Vladimir-csp** [comment]
Command line or Desktop Entry: the main difference is resulting unit's metadata. If Desktop Entry is given, its Name and Comment are used, plus arguments are parsed according to the spec if the entry has fields for them.
Also `uwsm app` and `app2unit` have terminal support (if Entry has `Terminal=true`, or `-T` argument is given, app will be launched in deafault terminal according to a [proposed spec](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3)). 

Is using path to entries a NixOS thing? ID is usually enough.

**Comment by fufexan** [comment]
> Is using path to entries a NixOS thing? ID is usually enough.

No, it's just that anyrun [already has the path](https://github.com/anyrun-org/anyrun/blob/d2017f224b2bfd7e33573c7070e7c3e2960c7dcc/plugins/applications/src/scrubber.rs#L8), but not the ID (basename).

> Also `uwsm app` and `app2unit` have terminal support (if Entry has `Terminal=true`, or `-T` argument is given, app will be launched in deafault terminal according to a [proposed spec](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3)).

If this is the case, then I'll make another uwsm-specific application plugin rather than try to modify the current one.

**Comment by Vladimir-csp** [comment]
> No, it's just that anyrun [already has the path](https://github.com/anyrun-org/anyrun/blob/d2017f224b2bfd7e33573c7070e7c3e2960c7dcc/plugins/applications/src/scrubber.rs#L8), but not the ID (basename).

Ah, ok, in this case the path is preferable, no need to search the entry if file is already known.

**Comment by fufexan** [comment]
Thanks for the clarifications!
