### ISSUE TITLE
`find_terminal_entry()` does not search for `xdg-terminal.list` in `BaseDirectory.xdg_config_home`

### ISSUE THREAD

**Issue by fufexan** [Vladimir-csp/uwsm#55]
https://github.com/Vladimir-csp/uwsm/blob/99f911ea23a8b5ccd2a3cba540f8065c2487b694/uwsm/main.py#L3191

Is this intentional or just an overlook? I see the [spec supports it](https://gitlab.freedesktop.org/terminal-wg/specifications/-/merge_requests/3/diffs#c67d0a5b8ca5f0691dd107280cbfb2e4316e26cc_0_108).

**Comment by Vladimir-csp** [comment]
`BaseDirectory.xdg_config_dirs` returns the whole hierarchy including `$XDG_CONFIG_HOME`, despite its name. Do you observe a different behavior?

**Comment by fufexan** [comment]
Yes, but that may be my setup's fault
```sh
› printenv XDG_CONFIG_DIRS | sed 's/:/\n/g'
/etc/xdg
/home/mihai/.nix-profile/etc/xdg
/home/mihai/.local/state/nix/profile/etc/xdg
/home/mihai/.local/state/nix/profile/etc/xdg
/etc/profiles/per-user/mihai/etc/xdg
/nix/var/nix/profiles/default/etc/xdg
/run/current-system/sw/etc/xdg
```

**Comment by Vladimir-csp** [comment]
`XDG_CONFIG_DIRS` should contain system part of the hierarchy, that is correct. But pyxdg object `xdg.BaseDirectory.xdg_config_dirs` returns contents of `XDG_CONFIG_HOME` + `XDG_CONFIG_DIRS`. It is not explicitly stated, but seems to be implied:

> A list of directory paths in which configuration may be stored, in preference order.

**Comment by fufexan** [comment]
Now that you point that out, I see it https://cgit.freedesktop.org/xdg/pyxdg/tree/xdg/BaseDirectory.py#n40.

I'll have to investigate why `xdg-terminals.list` isn't picked up.
Its contents are (based on <https://github.com/Vladimir-csp/xdg-terminal-exec/blob/master/xdg-terminals.list>):
```
/execarg_default:foot.desktop:--
```

However `uwsm app --` still tries to pick the first available option by searching .desktop files manually, and it wrongfully picks foot server which is already started.

**Comment by Vladimir-csp** [comment]
`/execart_default` directive is not a part of the spec, but a compatibility feature of xdg-terminal-exec, it is a long story.
Uwsm does not support it. To set default, just put:
```
foot.desktop
```
Foot accepts `-e` just fine.

**Comment by Vladimir-csp** [comment]
Fallback exclusions are part of the spec and are supported by uwsm.
```
-foot-server.desktop
```

**Comment by fufexan** [comment]
Thanks, this worked!
