### ISSUE TITLE
Hyprland doesn't stop immediately, if using loginctl terminate-user "" or reboot/poweroff

### ISSUE THREAD

**Issue by izmyname** [Vladimir-csp/uwsm#56]
When executing `loginctl terminate-user ""`,  `systemctl reboot`  or simply powering the laptop off, all services are stopped but Hyprland, itself, is stuck with the default wallpaper placeholder for about 30 secs before exiting to tty1 login prompt or rebooting/shutting the laptop down. If there are any flatpaks launched, they don't exit, either.

Removing all flatpaks from autostart in `hyprland.conf` doesn't fix the problem.

The output of `journalctl --user --since 05:58 `attached below.
[log.txt](https://github.com/user-attachments/files/17685410/log.txt)

**Comment by Vladimir-csp** [comment]
We've got a suspect.
```
Nov 09 05:58:00 archbtw systemd[10076]: Stopping MPD Notification...
...
Nov 09 05:58:25 archbtw systemd[10076]: Stopped MPD Notification.
```

**Comment by izmyname** [comment]
> We've got a suspect.
> 
> ```
> Nov 09 05:58:00 archbtw systemd[10076]: Stopping MPD Notification...
> ...
> Nov 09 05:58:25 archbtw systemd[10076]: Stopped MPD Notification.
> ```

Yup.

The problem was my previously mentioned `After=graphical-session.target `override. I changed it to mako.service and the problem is gone.

**Comment by Vladimir-csp** [comment]
Plus some graphical app is running in compositor's unit:
```
Nov 09 05:58:00 archbtw uwsm_hyprland.desktop[10697]: QDBusTrayIcon encountered a D-Bus error: QDBusError("org.freedesktop.DBus.Error.ServiceUnknown", "The name is not activatable")
```

Mako is starting right after `graphical-session.target` is deactivated.
```
Nov 09 05:58:25 archbtw systemd[10076]: Starting Lightweight Wayland notification daemon...
```

BTW, you can add a glob override `app-flatpak-.scope.d/deps.conf` with:
```
[Unit]
After=graphical-session.target
PartOf=graphical-session.target
```

**Comment by izmyname** [comment]
> Plus some graphical app is running in compositor's unit:

In my system, only telegram and openfreebuds apps have tray icons. Both are flatpaks, so probably one of them.



> Mako is starting right after `graphical-session.target` is deactivated.

It's started via DBus, when a notification is emitted. An override entry is just a leftover I never bothered to remove as I have other overrides for the service.



> BTW, you can add a glob override `app-flatpak-.scope.d/deps.conf` with:

I'll keep in mind, thanks for the info

**Comment by Vladimir-csp** [comment]
> > BTW, you can add a glob override app-flatpak-.scope.d/deps.conf with:
>
> I'll keep in mind, thanks for the info

In fact, I incorporated it into uwsm: d2c418727ed587eabf4cc697b6963cf013d38856

**Comment by Vladimir-csp** [comment]
> In my system, only telegram and openfreebuds apps have tray icons. Both are flatpaks, so probably one of them.

Ah, yes, scopes. Stdout/stderr would still go via Hyprland.

**Comment by izmyname** [comment]
Also, not that big deal to open a new issue, so I mention it here. There's a spelling error within uwsm app -h output. Should be `application`

```
uwsm app -h

positional arguments:
  args                  **Applicatoin** command line. The first argument can be either one of:
     
```
