### ISSUE TITLE
What are the requirements for check may-start?

### ISSUE THREAD

**Issue by autofool** [Vladimir-csp/uwsm#59]
I'm trying to start Hyprland on auto login with greetd.

```
/etc/greetd/config.toml

[terminal]
vt = 1

[default_session]
command = "tuigreet -t -r --remember-user-session --asterisks  --time-format '%A %d, %B %Y, %I:%M:%S %p' --user-menu -g 'Forward. Always.' --cmd /bin/bash"

[initial_session]
command = "/bin/bash"
user = "acp"
```

```
~/.bash_profile

#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if uwsm check may-start; then
  exec uwsm start hyprland.desktop
fi
```

Greetd always drops me in bash shell instead of starting Hyprland. If I log into another tty and run `uwsm, check may-start`, it always returns false.  If I remove check then Hyprland starts fine.

**Comment by Vladimir-csp** [comment]
Most probably login shell check fails, you can confirm with `uwsm check may-start -v`.

From `man bash`:

> A login shell is one whose first character of argument zero is a -, or one started with the --login option.

`uwsm check may-start` checks if parent process name starts with `-`. I'm not sure if just starting bash with `--login` option does affects its name, `login` sets it during normal tty login.

>  If I log into another tty and run uwsm, check may-start, it always returns false.

By default it checks for tty1, see `uwsm check may-start -h`.

Anyway, `may-start` might be considered a bit paranoid now that `uwsm start` includes tests for conflicting units. If you control startup parameters yourself, you may not need  `uwsm check may-start`.

I'll revisit this, some changes may be needed.

**Comment by Vladimir-csp** [comment]
In greetd autologin situation, if you do not need a fallback to shell, just use `uwsm start ...` directly.

**Comment by autofool** [comment]
That's what I ended up doing last night. Replaced `/bin/bash` with `uwsm start`.

**Comment by autofool** [comment]
For greetd cmd is `-a "-" bash`.  uwsm has check for that $0 start with "-".

**Comment by Vladimir-csp** [comment]
`-a "-bash" bash` then.

What I see on my machine: 

From login shell on a tty (executed by `login`):
```
$ echo $0
-bash
```
From interactive shell, initial state and then replication of a login shell:
```
$ echo $0
/bin/bash
$ exec -a -bash bash
May not start compositor:
  A compositor and/or graphical-session* targets are already active                                                                                                                       
$ echo $0
-bash
```
uwsm output means that `~/.profile` was sourced, so bash is indeed a login shell with a proper name.
