### ISSUE TITLE
OOM killer stops the compositor, not the process that caused it

### ISSUE THREAD

**Issue by loss-and-quick** [Vladimir-csp/uwsm#64]
## System Information
- **Distribution:** Arch Linux
- **Compositor:** Hyprland
## Description
I attempted to execute a fork bomb 
After performing this operation, the screen went black, and going to tty, I read logs indicating that the compositor had been terminated by the Out Of Memory (OOM) killer:
```
Nov 16 03:53:33 host systemd[1016]: wayland-wm@Hyprland.service: Consumed 8min 32.840s CPU time, 13.5G memory peak.
Nov 16 03:53:33 host systemd[1016]: wayland-wm@Hyprland.service: Triggering OnFailure= dependencies.
Nov 16 03:53:33 host systemd[1016]: Stopped Main service for Hyprland, An_intelligent_dynamic_tiling_Wayland_compositor.
Nov 16 03:53:33 host systemd[1016]: wayland-wm@Hyprland.service: Failed with result 'oom-kill'.
Nov 16 03:25:35 host systemd[1]: [user@1000.service](mailto:user@1000.service): A process of this unit has been killed by the OOM killer.
Nov 16 03:25:35 host systemd[1015]: [wayland-wm@Hyprland.service](mailto:wayland-wm@Hyprland.service): A process of this unit has been killed by the OOM killer.
```
## Steps to Reproduce
1. Open a terminal.
2. Execute the fork bomb command: `:(){ :|:& };:` or `python -c "memory_hog = [' ' * 10**6 for _ in iter(int, 1)]"`

## Expected Behavior
I expected the system to handle the fork bomb by killing the process of it.

## Actual Behavior
The OOM killer was triggered, resulting in the termination of compositor.

**Comment by loss-and-quick** [comment]
Using a fork bomb, I simulated the compilation of the project, as the original issue was discovered during the compilation of a Rust project.

**Comment by Vladimir-csp** [comment]
Was the terminal in a separate unit? Which process was killed? `journalctl --since today -g 'Out of memory: Killed process'`

**Comment by loss-and-quick** [comment]
> Was the terminal in a separate unit?
I don't know how to look it up.
The problem was originally caused as said by compiling Rust code, the terminal was inside vscode

**Comment by Vladimir-csp** [comment]
The combination of:
```
Nov 16 03:25:35 host systemd[1015]: [wayland-wm@Hyprland.service](mailto:wayland-wm@Hyprland.service): A process of this unit has been killed by the OOM killer.
```
and
```
Nov 16 03:25:35 host kernel: Out of memory: Killed process 15702 (chromium) total-vm:1212681700kB, anon-rss:231008kB, file>
```
Tells me that those processes were a part of `wayland-wm@Hyprland.service`, so application launching was not properly configured. 

Launch them in separate units via `uwsm app --`, or `uwsm-app --`,  (or use [app2unit](https://github.com/Vladimir-csp/app2unit/) if uwsm's wrapper is too slow on your setup).

See [this](https://github.com/Vladimir-csp/uwsm#3-applications-and-slices) and [this](https://wiki.hyprland.org/Useful-Utilities/Systemd-start/#launching-applications-inside-session)

I tried launching a memory hog in a terminal, OOM worked correctly:
```
Nov 16 13:05:54 host kernel: Out of memory: Killed process 18024 (python) total-vm:27928488kB, anon-rss:27910400kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:54692kB oom_score_adj:200                                                                                                                                                                                    
Nov 16 13:05:53 host systemd[2842]: app-Hyprland-qterminal@02f77be1.service: A process of this unit has been killed by the OOM killer.
```

**Comment by loss-and-quick** [comment]
> I guess that since applications (like console or vscode) are started by calling hyprland combinations, like `bind = $mainMod, Q, exec, $terminal`, they are bound to the compositor unit, and thus when the process is killed, the compositor unit is also closed as shown in the first logs



> Launch them in separate units via `uwsm app --`, or `uwsm-app --`, (or use [app2unit](https://github.com/Vladimir-csp/app2unit/) if uwsm's wrapper is too slow on your setup).

Okay, I'll try changing the launch method

**Comment by loss-and-quick** [comment]
I think the problem's solved
