### ISSUE TITLE
Environment inheritance issues

### ISSUE THREAD

**Issue by Ghosthree3** [Vladimir-csp/uwsm#65]
Since moving to uwsm to start/manage Hyprland I've found at least one issue related to environmental variable inheritance I'd like to know how to solve.

I use Kitty as my terminal (launched with `uwsm app --`), and in its config I have `open_url_with linkhandler`. `linkhandler` is a shell script file I have in `~/bin` which then opens the URL in an appropriate program based on the suffix.

This previously worked without issue but since switching my start process it would seem that the environment held by the shell/terminal is not passed to whatever magic python tool Kitty uses to call `linkhandler`. When clicking a link nothing happens, and this is written to the journal:
```
uwsm_hyprland.desktop[58486]: Traceback (most recent call last):
uwsm_hyprland.desktop[58486]:   File "/usr/bin/../lib/kitty/kitty/boss.py", line 2158, in doit
uwsm_hyprland.desktop[58486]:     open_url(url, program or get_options().open_url_with, cwd=cwd, extra_env=extra_env)
uwsm_hyprland.desktop[58486]:   File "/usr/bin/../lib/kitty/kitty/utils.py", line 260, in open_url
uwsm_hyprland.desktop[58486]:     return open_cmd(command_for_open(program), url, cwd=cwd, extra_env=extra_env)
uwsm_hyprland.desktop[58486]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
uwsm_hyprland.desktop[58486]:   File "/usr/bin/../lib/kitty/kitty/utils.py", line 254, in open_cmd
uwsm_hyprland.desktop[58486]:     return subprocess.Popen(
uwsm_hyprland.desktop[58486]:            ^^^^^^^^^^^^^^^^^
uwsm_hyprland.desktop[58486]:   File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
uwsm_hyprland.desktop[58486]:     self._execute_child(args, executable, preexec_fn, close_fds,
uwsm_hyprland.desktop[58486]:   File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
uwsm_hyprland.desktop[58486]:     raise child_exception_type(errno_num, err_msg, err_filename)
uwsm_hyprland.desktop[58486]: FileNotFoundError: [Errno 2] No such file or directory: 'linkhandler'
```
`~/bin` is of course in my shell's `$PATH` (defined in `~/.zshenv`), but it would seem that the forked python process is using the `$PATH` defined by systemd instead (`systemctl --user show-environment` is missing several components in `$PATH` that I have added in `~/.zshenv`).

The problem goes away if I use the full path to the script file (ie. `open_url_with /home/user/bin/linkhandler`), but then I run into the problem that the script itself depends on an environmental variable (`$BROWSER`) to function, which is also defined in `~/.zshenv`.

Hardcoding everything to avoid inheritance seems like the wrong solution here, so what should I do? Should I import my entire environment into systemd post-login?

I'm sure there are other situations in which this problem surfaces, but I have not run into any more as of yet.

**Comment by Vladimir-csp** [comment]
Uwsm operates with POSIX shell, so some additional configuration is needed for sharing vars with shells that do not support/use `~/.profile`.

I've updated README and moved environment sources summary to a more visible [place](https://github.com/Vladimir-csp/uwsm#4-environments-and-shell-profile).

**Comment by izmyname** [comment]
IMHO, PATH looks exactly like something, one should define in ` ~/.config/environment.d/*.conf`.

**Comment by Ghosthree3** [comment]
Thanks, I must have missed or misunderstood the information when I was first setting up uwsm, but it's much clearer now as its own step.

**Comment by Vladimir-csp** [comment]
> IMHO, PATH looks exactly like something, one should define in  `~/.config/environment.d/*.conf`.

And the bonus is: it's shell-agnostic. Potential downside is quite a wide scope, but in case of `PATH` it seems to be perfect.

**Comment by Ghosthree3** [comment]
Using shell specific `.profile` files for env vars is very old configuration advice (if you managed to avoid the `.rc` file advice), even for `PATH`, and the only reason I had my (very old) setup the way it was. But, it is now updated to use the more modern approach.

**Comment by izmyname** [comment]
> Using shell specific `.profile` files for env vars is very old configuration

Yep, I don't see the point in using .profile for global vars, either.

Btw I expressed some thoughts about vars' usage in [this comment](https://github.com/hyprwm/Hyprland/discussions/8204#discussioncomment-11274700).

**Comment by izmyname** [comment]
> IMHO, PATH looks exactly like something, one should define in ` ~/.config/environment.d/*.conf`.

Correcting myself here. `~/.config/environment.d/*.conf` vars only sourced, when the graphical session starts. For things, like `$PATH` and other non-GUI-related stuff, use `.zshenv `, `.profle`, `.bash_profile` or whatever file your shell provides. See [my reply](https://github.com/hyprwm/Hyprland/discussions/8204#discussioncomment-11501768)

**Comment by Vladimir-csp** [comment]
`~/.config/environment.d/*.conf` has nothing to do with graphical sessions. It is applied to activation environment. That is given to service units.

**Comment by izmyname** [comment]
And, as I understand, activation environment happens when `uwsm` starts a graphical session.

Or, if a compositor started without uwsm, it's handled by `dbus-update-activation-environment --systemd ` hack in a compositor's config.

**Comment by Vladimir-csp** [comment]
Systemd activation environment exists with or without a graphical session, it is what user's systemd process gives to the services it starts. Classic dbus has its own, dbus-broker just operates with systemd's one.

UWSM (or other session managers) put appropriate variables there before graphical session starts, and remove them after it is stopped.

**Comment by izmyname** [comment]
Well, that's confusing. What a mess.

Anyway, I think, for an end user it's enough to stick to a rule: non-graphical session - related vars - shell config, graphical - environment.d/uwsm.

**Comment by Vladimir-csp** [comment]
Since environment preloader sources shell profile, whatever was set there affects both login shell environment and graphical environment.

`environment.d` affects user services, all of them, when each is started.

**Comment by Ghosthree3** [comment]
> Correcting myself here. `~/.config/environment.d/*.conf` vars are only sourced, when the graphical session starts. For things, like `$PATH` and other non-GUI-related stuff, use `.zshenv `, `.profle`, `.bash_profile` or whatever file your shell provides. See [my reply](https://github.com/hyprwm/Hyprland/discussions/8204#discussioncomment-11501768)

Doesn't this put me back to where I started with my PATH issues? Maybe I should define it in both?
