### ISSUE TITLE
Hyprland session exits on stopping a Podman container

### ISSUE THREAD

**Issue by mexanoz** [Vladimir-csp/uwsm#67]
As the title says, an uwsm-managed Hyprland session exits when a podman container is stopped. I'm not really sure what to make of it, but here is the info I have:
- Hyprland is specifically **not** crashing, it is receiving a SIGTERM (15) and exiting normally.
- It only happens when using uwsm and not when launching Hyprland directly.
- It reproduces both when using SDDM to launch a session and when launching it from the TTY.
- It happens when stopping any podman container, be it via `podman stop`, exiting from an interactive container or a non-interactive container stopping by itself. Before that the container runs normally.
- I did not test any other uwsm-managed sessions.

The logs below were obtained by launching a container with `podman start -it debian:12-slim` and immediately stopping it with ^D.

Tail of `hyprland.log` with `debug.disable_logs=false`:
```
[LOG] Hyprland received signal 15
[LOG] Hyprland is stopping!
[LOG] Kicked off the event loop! :(
```

Part of `journalctl`:
```
ноя 17 21:42:15 pcbell-arch systemd[60188]: Started libcrun container.
ноя 17 21:42:17 pcbell-arch podman[62690]: 2024-11-17 21:42:17.075869777 +0500 +05 m=+1.441203383 container init c9f13aea14e3a0ebb7a645070cc02659ed61c713221e81cec940cbb4108d4164 (image=docker.io/l
ibrary/debian:12-slim, name=laughing_brown)
ноя 17 21:42:17 pcbell-arch podman[62690]: 2024-11-17 21:42:17.089549769 +0500 +05 m=+1.454883375 container start c9f13aea14e3a0ebb7a645070cc02659ed61c713221e81cec940cbb4108d4164 (image=docker.io/
library/debian:12-slim, name=laughing_brown)
ноя 17 21:42:17 pcbell-arch podman[62690]: 2024-11-17 21:42:17.106482418 +0500 +05 m=+1.471816024 container attach c9f13aea14e3a0ebb7a645070cc02659ed61c713221e81cec940cbb4108d4164 (image=docker.io
/library/debian:12-slim, name=laughing_brown)
ноя 17 21:42:17 pcbell-arch laughing_brown[62712]: root@c9f13aea14e3:/#
ноя 17 21:42:17 pcbell-arch laughing_brown[62712]: exit
ноя 17 21:42:17 pcbell-arch podman[62690]: 2024-11-17 21:42:17.796190301 +0500 +05 m=+2.161523959 container died c9f13aea14e3a0ebb7a645070cc02659ed61c713221e81cec940cbb4108d4164 (image=docker.io/l
ibrary/debian:12-slim, name=laughing_brown)
ноя 17 21:42:18 pcbell-arch podman[62719]: 2024-11-17 21:42:18.055539643 +0500 +05 m=+0.228596464 container cleanup c9f13aea14e3a0ebb7a645070cc02659ed61c713221e81cec940cbb4108d4164 (image=docker.i
o/library/debian:12-slim, name=laughing_brown)
ноя 17 21:42:18 pcbell-arch uwsm_Hyprland[62450]: 16:42:18 [INFO] (main) Goodbye!
ноя 17 21:42:18 pcbell-arch uwsm_Hyprland[62450]: 16:42:18 [INFO] (main) Removed socket at "/run/user/1000/swww-wayland-1.socket"
ноя 17 21:42:18 pcbell-arch systemd[60188]: Stopped target XDG Autostart for session of Hyprland Wayland compositor.
```

- OS: Arch Linux
- linux 6.11.8-arch1-2
- systemd 256.8
- uwsm 0.20.4-1 (AUR package)
- hyprland-git 0.45.0.r29.af83c825-1 (also happened with the package from the official repo)
- podman 5.3.0

**Comment by Vladimir-csp** [comment]
Is podman being run in a unit? That is a terminal that was launched via `uwsm app --` or other wrapper? This sounds similar to #45.

**Comment by mexanoz** [comment]
It wasn't. It did indeed stop happening when I added `uwsm app --` to the terminal launch command. I appreciate the direction, I didn't catch that part from the documentation.

**Comment by id0o0bi** [comment]
I've noticed when you do `podman run`, the MainPID of the service is changed to the conmon PID!, so likely conmon is doing some notify work and changed the MainPID, thus when you stop the container. the whole session gets teared down. The work around I get from deepseek is to use a systemd-run to use podman.
