### ISSUE TITLE
Build error on Ubuntu 24.10.1

### ISSUE THREAD

**Issue by vaskark** [Vladimir-csp/uwsm#74]
meson setup --prefix=/usr/local -Duuctl=enabled -Dfumon=enabled -Duwsm-app=enabled build:

```
The Meson build system
Version: 1.5.1
Source dir: /home/vaskark/work/uwsm
Build dir: /home/vaskark/work/uwsm/build
Build type: native build

meson.build:3:11: ERROR: Command `/usr/bin/sh version.sh` failed with status 128.

A full log can be found at /home/vaskark/work/uwsm/build/meson-logs/meson-log.txt

```
I have the deps installed (afaik). Can anyone offer some help?
Thanks.

**Comment by Vladimir-csp** [comment]
What does `./version.sh` produce?

**Comment by vaskark** [comment]
./version.sh:

`fatal: No names found, cannot describe anything.
`

**Comment by Vladimir-csp** [comment]
Perhaps you have shallow git copy, i'll fix the script.

**Comment by vaskark** [comment]
> Perhaps you have shallow git copy, i'll fix the script.

I did do a shallow copy. Apologies. Should have thought of that. I'll do a proper clone later and report back.

**Comment by vaskark** [comment]
Works now. Many thanks.
