### ISSUE TITLE
Exposing ssh-agent to applications in session

### ISSUE THREAD

**Issue by jeslinmx** [Vladimir-csp/uwsm#75]
On my NixOS system, the KeePassXC flatpak cannot see $SSH_AUTH_SOCK and thus cannot inject keys into the agent when Hyprland is started from a display manager, but it can when Hyprland is started directly from a login shell.

(I presume that) the problem is that the display manager does not pass SSH_AUTH_SOCK to the compositor, or the ssh-agent systemd user service has not yet started when the compositor is launched, or I might be completely wrong here. I am trying to understand what is the correct way to go about doing this:

- Call ssh-agent from shell profile? (preferably not, as I prefer to keep the ssh-agent as a systemd unit)
- Export SSH_AUTH_SOCK from `.config/uwsm/env`? (doesn't seem to work for me)
- Add SSH_AUTH_SOCK to UWSM_FINALIZE_VARNAMES? (this seems like the most correct option from reading the docs, but I'm not sure where I am supposed to add this declaration)

I suppose my question is how to have an arbitrary environment variable be injected into the session environment, if the value is not declared by myself but by some other systemd unit. Hope my question is clear as this systemd/session management stuff is very new to me!

**Comment by Vladimir-csp** [comment]
If `ssh-agent.service` starts before `wayland-wm@.service`, its values should be available to services, including compositor's context. Service itself has `Before=graphical-session-pre.target`, so **if** it is started during \[graphical\] sesison startup transactions, it should be started way before that. Maybe it is not wanted or explicitly started by anything on your system when starting session via DM.

Now that you mention it, I do not know how exactly it is started on my system. It is not wanted by anything, so it is not enabled. I suspect gnome-keyring-daemon starts it explicitly.

Try adding `WantedBy=graphical-session-pre.target` to `ssh-agent.service` via a drop-in, then enable it. See if it is started properly after that.

**Comment by jeslinmx** [comment]
You're right, it's being `WantedBy` default.target rather than anything started by DM; this is the default when the ssh-agent unit is created by Home Manager's `services.ssh-agent.enable`.

I tried changing it to being both WantedBy and Before graphical-session-pre.target, and now it starts before graphical-session, wayland-wm@, and around the same time as wayland-wm-env, but it isn't accessible to KeePassXC. (to be clear, prior to these changes, it was already being started before these things, since it was being started under default.target)

For what it's worth, this is my ssh-agent.service as of right now:

```
[Install]                                                                                            
WantedBy=graphical-session-pre.target                                                                
                                                                                                     
[Service]                                                                                            
ExecStart=/nix/store/nfjjkzr25i7qj2r0vslb242jbadb1k4j-openssh-9.9p1/bin/ssh-agent -D -a %t/ssh-agent 
                                                                                                     
[Unit]                                                                                               
Before=graphical-session-pre.target                                                                  
Description=SSH authentication agent                                                                 
Documentation=man:ssh-agent(1)                                                                       
```

I tried gnome-keyring-daemon too, with both ssh-agent explicitly enabled and not, it didn't help either.

I actually have a very poor understanding of how systemd user units relate to the various targets and uwsm services, and how they interact in terms of environment variables. Do you have any sources that explain these things?

**Comment by Vladimir-csp** [comment]
Ok, I see it does not use any wrapper that would export the vars to activation environments. It's a Debian thing then.
But it uses predictable socket path of `%t/ssh-agent`, (`${XDG_RUNTIME_DIR}/ssh-agent`).

`WantedBy=default.target` is ok, no need to change this.
`Before=graphical-session-pre.target` is a useful addition. If NixOS does ship with this, it might be a good idea to request it.
The missing piece is something that delivers `SSH_AUTH_SOCK` to activation environments. In Debian `ssh-agent.service` runs a wrapper that does it. In your case I suspect it might be some code in shell-specific profile, like `~/.bash-profile` that is invoked only in login shell.

**Comment by Vladimir-csp** [comment]
IMHO the proper solution would be for `ssh-agent.service` itself to do this. Something like:
```
ExecStartPost=systemctl --user set-environment "SSH_AUTH_SOCK=%t/ssh-agent"
ExecStopPost=systemctl --user unset-environment SSH_AUTH_SOCK
```

**Comment by jeslinmx** [comment]
> IMHO the proper solution would be for `ssh-agent.service` itself to do this. Something like:
> 
> ```
> ExecStartPost=systemctl --user set-environment "SSH_AUTH_SOCK=%t/ssh-agent"
> ExecStopPost=systemctl --user unset-environment SSH_AUTH_SOCK
> ```

This worked! Thank you for teaching me about set-environment! I may make a PR to home-manager to add `Before=graphical-session-pre.target` and those 2 lines to the ssh-agent service it creates.
